name: Update piped-video-enhancer Domains

on:
  schedule:
    - cron: "0 1-2 * * 3-5"
  workflow_dispatch:

jobs:
  update_script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Execute Script
        id: execute_script
        run: |
          python ${{ github.workspace }}/piped-video-enhancer/update_script.py
      - name: Print Script Output
        run: echo "${{ steps.execute_script.outputs.script_output }}"
      - name: Commit and push changes
        run: |
          cd ${{ github.workspace }}
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update piped-video-enhancer domains"
          git push origin main
