name: Update piped-video-enhancer Domains

on:
  schedule:
    - cron: "0 2 * * 1-5"
  workflow_dispatch:

jobs:
  update_script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: pip install requests
      - run: python piped-video-enhancer/update_script.py
      - run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add piped-video-enhancer/index.js
          git diff-index --quiet HEAD || git commit -m "Update Domains"
