name: Update piped-video-enhancer Domains

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Requests Library
        run: |
          pip install requests
          pip install re

      - name: Execute Script
        run: python piped-video-enhancer/update_script.py

      - name: Commit and Push Changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add piped-video-enhancer/index.js
          git commit -m "Update user script"
          git push
